In [3]:
import numpy as np

# 4 tokens, embedding size = 3
X = np.array([
    [1.0, 0.0, 1.0],   # I
    [1.0, 1.0, 0.0],   # love
    [0.0, 1.0, 1.0],   # deep
    [0.0, 0.0, 1.0],   # learning
])


In [6]:
print(X)

[[1. 0. 1.]
 [1. 1. 0.]
 [0. 1. 1.]
 [0. 0. 1.]]


In [8]:
X.T

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 1.]])

In [7]:
# For similrity dot product
scores = X @ X.T
print(scores)

[[2. 1. 1. 1.]
 [1. 2. 1. 0.]
 [1. 1. 2. 1.]
 [1. 0. 1. 1.]]


In [9]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / exp_x.sum(axis=-1, keepdims=True)

weights = softmax(scores)
print(weights)

[[0.47536689 0.1748777  0.1748777  0.1748777 ]
 [0.19661193 0.53444665 0.19661193 0.07232949]
 [0.1748777  0.1748777  0.47536689 0.1748777 ]
 [0.29692274 0.10923177 0.29692274 0.29692274]]


In [14]:
np.exp(scores - np.max(scores, axis=-1, keepdims=True))

array([[1.        , 0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 1.        , 0.36787944, 0.13533528],
       [0.36787944, 0.36787944, 1.        , 0.36787944],
       [1.        , 0.36787944, 1.        , 1.        ]])